faceapp_api/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('user.urls')),
    path('api/account/',include('user.api.urls')),
    path('',include('main.urls')),
    path('api/',include('main.api.urls')),
]



from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


main/urls.py
from django.urls import path,include,reverse_lazy
from .views import  homeview
app_name='main'
urlpatterns = [
path('',homeview,name='homeview'),
]

user/api/urls.py
from django.urls import path
from rest_framework_jwt.views import obtain_jwt_token,refresh_jwt_token
from .views import  loginApi,register
urlpatterns = [
    # Your URLs...
    # path('token/', obtain_jwt_token, name='token_obtain_pair'),
    path('token/', loginApi.as_view(), name='token'),
    path('token-refresh/',refresh_jwt_token, name='rtoken'),
    path('register/',register, name='signup'),
]
# $ curl -X POST -H "Content-Type: application/json" -d '{"username":"admin","password":"password123"}' http://localhost:8000/api-token-auth/



# $ curl -X POST -H "Content-Type: application/json" -d '{"token":"<EXISTING_TOKEN>"}' http://localhost:8000/api-token-refresh/

# $ curl -H "Authorization: JWT <your_token>" http://localhost:8000/protected-url/

user/urls.py
from django.urls import path,include,reverse_lazy

app_name='user'
urlpatterns = [

    
]

user/models.py
from django.db import models

from django.contrib.auth.models import User

from django.db.models.signals import post_save
from django.dispatch import receiver
# from phonenumber_field.modelfields import PhoneNumberField #<---
from django.conf import settings

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    location = models.CharField(max_length=300, blank=True)
    phone = models.CharField(blank=True,max_length=16)

    email_confirmed = models.BooleanField(default=False)

    '''
    Installation
    pip install django-phonenumber-field
    pip install phonenumbers

    INSTALLED_APPS = [
    ...
    'phonenumber_field',
    ...
    ]
    from phonenumber_field.modelfields import PhoneNumberField
    from phonenumber_field.formfields import PhoneNumberField

    phone = PhoneNumberField(blank=True,help_text="plase enter your phone number",max_length=16)

    phone = PhoneNumberField(max_length=16, help_text='Contact phone number mast be 8 chareture')



    Internally, PhoneNumberField is based upon CharField and by default represents the number as a string of an international phonenumber in the database (e.g '+41524204242').

Representation can be set by PHONENUMBER_DB_FORMAT variable in django settings module. This variable must be one of 'E164', 'INTERNATIONAL', 'NATIONAL' or 'RFC3966'. Recommended is one of the globally meaningful formats 'E164', 'INTERNATIONAL' or 'RFC3966'. 'NATIONAL' format require to set up PHONENUMBER_DEFAULT_REGION variable.

The object returned is a PhoneNumber instance, not a string. If strings are used to initialize it, e.g. via MyModel(phone_number='+41524204242') or form handling, it has to be a phone number with country code.

    +[country code][number]x[extension]
    +12223334444x55

    Use the |phone template filter to attempt to display a formatted phone number from arbitrary text. Use the |raw_phone template filter to display the raw, un-formatted value.

    Use property .is_E164 to check if a PhoneNumber object is in E164 format.

    Also provided are .is_standard (E164 but with extensions allowed) and .is_usa
    '''

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

user/forms.py

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.utils.translation import gettext_lazy as _

from django.core.exceptions import ValidationError
from django import forms
# from phonenumber_field.formfields import PhoneNumberField

"""
 Here we are defining four fields namely username, email, password1 and password2; with their own clean_<field_name>() method (except for password1 field).
 Pay close attention to the widget keyword argument in both the password fields. The widget keyword argument allows us to change the default widget of the field.
 Recall that by default, CharField is rendered as text field (i.e <input type="text" ... >).
 To render the CharField as password field we have set widget keyword argument to forms.PasswordInput.

The clean_username() and clean_email() methods check for duplicate username and email respectively.
The clean_password2() method checks whether the password entered in both the fields matches or not. Finally, the save() method saves the data into the database.
"""
class CustomUserCreationForm(forms.ModelForm):
    username = forms.CharField( min_length=4, label= _('Unsername'),max_length=150, help_text='Please file the form with valid name ')
    email = forms.EmailField(label=_('Email'),help_text='Please file the form with valid email id ')
    password1 = forms.CharField(label=_("Password"),widget=forms.PasswordInput,min_length=6,help_text='<li>Password Should be at least 6 character long</li>')
    password2 = forms.CharField(label=_("Confirm Password"),widget=forms.PasswordInput,min_length=6)
    phone = forms.CharField(max_length=14,min_length=11,label=_("Phone"),help_text=_('Use this format +8801*******'))
    address=forms.CharField(max_length=200,label=_("Address"),widget=forms.Textarea(attrs={'rows':"2"}))
    class Meta:
        model=User
        fields=('username','email','phone','address','password1', 'password2')
        # labels = {
        #     'username': _('Unsername'),
        #     "phone":_('PhoneNumber'),
        #     "password1":_('Password'),
        #     "password2":_('Confirm Password'),
        # }
        # help_texts = {
        #
        #     'phone': _('Use this forment +8801777777777'),
        #     "password1":_('Password mast be 8 chareture'),
        # }
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2


"""
Notice that CustomUserCreationForm inherits from forms.Form class rather than forms.ModelForm.

"""

class loginform(forms.Form):
    username=forms.CharField(max_length=20,required=True,label=_("Username"))
    password= forms.CharField(label=_("Password"),widget=forms.PasswordInput)

user/api/views.py
import  json
#django
from django.http import JsonResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
#djangoRest
from rest_framework.decorators import api_view, permission_classes
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .utils import jwt_response_payload_handler
from rest_framework.permissions import  AllowAny
#other
from rest_framework_jwt.settings import api_settings
jwt_payload_handler = api_settings.JWT_PAYLOAD_HANDLER
jwt_encode_handler = api_settings.JWT_ENCODE_HANDLER


# jwt_response_payload_handler = api_settings.JWT_PAYLOAD_GET_USER_ID_HANDLER

def hendel_token(user):
    payload = jwt_payload_handler(user)
    token = jwt_encode_handler(payload)
    r=jwt_response_payload_handler(token,user)
    return r


class loginApi(APIView):
    permission_classes=[AllowAny]
    def post(self, request):

        data=None
        username=None
        password=None
        jdata=request.data
        print(request.data)
        try:
            #if data send as a json forment
            data=json.loads(jdata)

            username=data['username']
            password=data['password']
            # print(username)
        except:
            username=jdata.get('username')
            password=jdata.get('password')
            # print(username,'cnt load ')
            # print('21')
        finally:
            if username and password:
                user=authenticate(request,username=username,password=password)
                print(user)
                # login(request,user)
                if user is None:

                    return Response("[{'details':'username and password incorrect'}]", status=status.HTTP_400_BAD_REQUEST)

                else:
                    # payload = jwt_payload_handler(user)
                    # token = jwt_encode_handler(payload)
                    # r=jwt_response_payload_handler(token,user)
                    r=hendel_token(user)
                    print(r)

                return Response(r, status=status.HTTP_200_OK)



            else:
                return Response({'details':'username and password incorrect'}, status=status.HTTP_400_BAD_REQUEST)
            return Response({'details':'username and password incorrect'}, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
@permission_classes([AllowAny])
def register(request):
    data=None
    username=None
    password=None
    jdata=request.data
    try:
        #if data send as a json forment
        data=json.loads(jdata)
        username=data['username']
        password=data['password']
        email=data['email']
        # print(username)
    except:
        username=jdata.get('username',None)
        password=jdata.get('password',None)
        email=jdata.get('email',None)
    finally:
        if username and password and email:
            t=User.objects.filter(email__exact=email)
            # print(t)
            if len(t)==0:
                t=User.objects.filter(username__exact=username)
                if(len(t)!=0):
                    return Response({'details':f"this username='{username}' is already taken"},status=status.HTTP_203_NON_AUTHORITATIVE_INFORMATION)

                user=User.objects.create_user(username=username, email=email,password=password)
                # user.set_password(password)
                user.save()
                # user=authenticate(password=password, username=user.username)
                login(request,user)
                # login()
                r=hendel_token(user)
                return Response(r,status=status.HTTP_201_CREATED)
            else:
                return Response({'details':f'this email=\'{email}\' is already taken '},status=status.HTTP_203_NON_AUTHORITATIVE_INFORMATION)

user/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
    medicust
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link href="https://use.fontawesome.com/releases/v5.0.1/css/all.css" rel="stylesheet">

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

  </head>
  <body>

<style media="screen">


a.navbar-brand {
  font-weight: lighter;
  border-block-end-color: inherit;
  border: 2px solid;
  border-color: #8e5470;
  border-radius: 87px;
  padding: 10px;

}

div#navbarTogglerDemo03 {
    list-style: none;
}
</style>
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{%url 'main:homeview'%}">MEDICUST</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">

<li class="nav-item">
</li>
<li class="nav-item">

</li>
    </ul>

  </div>
</nav>


<!-- <form class="form-inline my-2 my-lg-0">
  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form> -->
<!--
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>

  {%url 'services:emergency_medicin_request_list' as emergency_medicin_request_list%}

  <a class="nav-link {%if request.get_full_path == emergency_medicin_request_list%}active{%endif%}" href="{%url 'services:emergency_medicin_request_list'%}">Medicine</a>
  {% endif %} -->
    {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}
  {% endif %}



    <div class="container">
      {% block content %}
      {% endblock %}
      {% block body %}
      {% endblock %}
    </div>


  </body>
</html>